# -*- coding: utf-8 -*-
"""EGBI222 Pair Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ekELgcEpO2kXgJXop8MY11h733KMrdfj

# Sports Car Data Analysis

This repository contains a Jupyter Notebook that performs an exploratory data analysis on a dataset of sports cars. The analysis includes visualizations and summary statistics to understand various aspects of the data, such as price trends, engine characteristics, and manufacturer performance.

## Notebook Contents

The analysis is structured into several sections within the notebook, each addressing a different area of the sports car dataset.

### Setup and Imports

This initial section sets up the environment by importing necessary Python libraries for data manipulation and visualization, including `pandas`, `numpy`, `matplotlib.pyplot`, and `seaborn`. It also configures plotting styles and handles potential warnings.

### Year Analysis

The `year_analysis` function explores the dataset based on the year of manufacture. It generates two plots:

*   **Price Trend by Year**: This plot (visible in the notebook output below the corresponding code cell) shows how the average price of sports cars has changed over the years, with error bars indicating the variability in prices for each year. This helps identify price trends and fluctuations.
*   **Models by Year**: This bar chart (also in the notebook output for the `year_analysis` cell) illustrates the number of new sports car models introduced each year, providing insights into the volume of production over time.

### Engine Size Analysis

The `engine_analysis` function focuses on the characteristics of the cars' engines. It produces two visualizations:

*   **Engine Size Distribution**: A histogram (displayed in the notebook output for `engine_analysis`) showing the frequency of different engine sizes in the dataset. This helps understand the common engine sizes among sports cars.
*   **Power Efficiency by Brand**: A box plot (part of the `engine_analysis` output) that compares the horsepower generated per liter of engine displacement across different manufacturers. This highlights which brands are more efficient in terms of power output relative to engine size.

### Price Analysis

The `price_analysis` function provides a detailed look at the distribution of sports car prices. It generates:

*   **Price Distribution**: A histogram (shown in the notebook output for `price_analysis`) illustrating the frequency of different price points. Lines on the histogram indicate the mean and median prices, helping to understand the typical price range and any skewness in the distribution.
*   **Price Box Plot**: A box plot (also in the `price_analysis` output) offering a visual summary of the price distribution, including quartiles and potential outliers. This provides a quick overview of the spread and central tendency of prices.

### Manufacturer Analysis

The `manufacturer_analysis` function examines the dataset from the perspective of different manufacturers. It creates three plots:

*   **Market Share**: A pie chart (in the notebook output for `manufacturer_analysis`) showing the proportion of cars from the top manufacturers in the dataset, indicating their market presence.
*   **Average Price by Make**: A bar chart (part of the `manufacturer_analysis` output) displaying the average price of cars for the top manufacturers, allowing for easy comparison of pricing strategies between brands.
*   **Price Range by Brand**: A box plot (also in the `manufacturer_analysis` output) illustrating the distribution of prices for the top manufacturers, showing the variability in pricing within each brand and identifying potential outliers.

### Summary Statistics

The `format_summary_statistics` function (code and output visible in the notebook) generates a detailed table of descriptive statistics for all numerical columns in the dataset. This table includes important measures such as count, mean, standard deviation, minimum, maximum, and quartiles, providing a comprehensive quantitative summary of the data.

## How to View the Outputs

All the generated graphs and the summary statistics table are displayed directly within the output cells of the Jupyter Notebook. To view them, simply run the code cells in sequence.

---
*(This README is formatted to be approximately two pages on A4 when rendered from Markdown.)*
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")
plt.rcParams['font.size'] = 10

# YEAR ANALYSIS

def year_analysis(df):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6))

    year_stats = df.groupby('Year')['Price'].agg(['mean', 'std']).reset_index()
    ax1.errorbar(year_stats['Year'], year_stats['mean'], yerr=year_stats['std'],
                marker='o', linewidth=2, markersize=8, capsize=5, color='blue')
    ax1.set_title('Price Trend by Year', fontweight='bold', fontsize=14)
    ax1.set_xlabel('Year')
    ax1.set_ylabel('Average Price ($)')
    ax1.grid(True, alpha=0.3)
    ax1.tick_params(axis='x', rotation=45)

    year_counts = df['Year'].value_counts().sort_index()
    ax2.bar(year_counts.index, year_counts.values, alpha=0.7, color='green')
    ax2.set_title(' Models by Year', fontweight='bold', fontsize=14)
    ax2.set_xlabel('Year')
    ax2.set_ylabel('Number of Models')
    ax2.tick_params(axis='x', rotation=45)

    plt.suptitle('YEAR ANALYSIS', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

df = load_sports_car_data()
year_analysis(df)

# ENGINE SIZE ANALYSIS

def engine_analysis(df):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6))

    ax1.hist(df['Engine_Size'], bins=25, alpha=0.7, color='orange', edgecolor='black')
    mean_engine = df['Engine_Size'].mean()
    ax1.axvline(mean_engine, color='red', linestyle='--', linewidth=2, label=f'Mean: {mean_engine:.1f}L')
    ax1.set_title('Engine Size Distribution', fontweight='bold', fontsize=14)
    ax1.set_xlabel('Engine Size (L)')
    ax1.set_ylabel('Frequency')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    df['HP_per_Liter'] = df['Horsepower'] / df['Engine_Size']
    top_makes = df['Make'].value_counts().head(6).index
    df_eff = df[df['Make'].isin(top_makes)]
    sns.boxplot(data=df_eff, x='Make', y='HP_per_Liter', ax=ax2, palette='viridis')
    ax2.set_title('Power Efficiency by Brand', fontweight='bold', fontsize=14)
    ax2.set_xlabel('Manufacturer')
    ax2.set_ylabel('HP per Liter')
    ax2.tick_params(axis='x', rotation=45)

    plt.suptitle('ENGINE SIZE ANALYSIS', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

engine_analysis(df)

# PRICE ANALYSIS

def price_analysis(df):
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6))

    ax1.hist(df['Price'], bins=30, alpha=0.7, color='royalblue', edgecolor='black')
    mean_price = df['Price'].mean()
    median_price = df['Price'].median()
    ax1.axvline(mean_price, color='red', linestyle='--', linewidth=2, label=f'Mean: ${mean_price:,.0f}')
    ax1.axvline(median_price, color='orange', linestyle='--', linewidth=2, label=f'Median: ${median_price:,.0f}')
    ax1.set_title('Price Distribution', fontweight='bold', fontsize=14)
    ax1.set_xlabel('Price ($)')
    ax1.set_ylabel('Frequency')
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    box_plot = ax2.boxplot(df['Price'], patch_artist=True, vert=True)
    box_plot['boxes'][0].set_facecolor('lightblue')
    box_plot['boxes'][0].set_alpha(0.7)
    ax2.set_title('Price Box Plot', fontweight='bold', fontsize=14)
    ax2.set_ylabel('Price ($)')
    ax2.grid(True, alpha=0.3)

    plt.suptitle('PRICE ANALYSIS', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

price_analysis(df)

# MANUFACTURER ANALYSIS

def manufacturer_analysis(df):
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(18, 6))

    make_counts = df['Make'].value_counts().head(8)
    colors = plt.cm.Set3(np.linspace(0, 1, len(make_counts)))
    ax1.pie(make_counts.values, labels=make_counts.index, autopct='%1.1f%%',
            colors=colors, startangle=90)
    ax1.set_title('Market Share', fontweight='bold', fontsize=14)

    avg_prices = df.groupby('Make')['Price'].mean().sort_values(ascending=False).head(8)
    bars = ax2.bar(range(len(avg_prices)), avg_prices.values, color='coral', alpha=0.8)
    ax2.set_xticks(range(len(avg_prices)))
    ax2.set_xticklabels(avg_prices.index, rotation=45, ha='right')
    ax2.set_title('Average Price by Make', fontweight='bold', fontsize=14)
    ax2.set_ylabel('Average Price ($)')
    ax2.ticklabel_format(style='plain', axis='y')

    for bar, price in zip(bars, avg_prices.values):
        ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5000,
                f'${price:,.0f}', ha='center', va='bottom', fontsize=9)

    top_makes = df['Make'].value_counts().head(6).index
    df_top = df[df['Make'].isin(top_makes)]
    sns.boxplot(data=df_top, x='Make', y='Price', ax=ax3, palette='Set2')
    ax3.set_title('Price Range by Brand', fontweight='bold', fontsize=14)
    ax3.tick_params(axis='x', rotation=45)

    plt.suptitle('MANUFACTURER ANALYSIS', fontsize=16, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

manufacturer_analysis(df)

# SUMMARY STATISTICS FUNCTIONS
def format_summary_statistics(df):
    summary_df = df.describe().transpose()

    print("Summary Statistics")
    display(summary_df.style.format("{:,.2f}").set_properties(**{'font-size': '10pt'}))

format_summary_statistics(df)